let helpers = module.exports = {}

helpers.add = require('./add')
helpers.capitalize = require('./capitalize')
helpers.encodeDasherize = require('./encodeDasherize')
helpers.eq = require('./eq')
helpers.join = require('./join')
helpers.modulo = require('./modulo')
helpers.moment = require('./moment')
helpers.momentFromNow = require('./momentFromNow')
helpers.numeral = require('./numeral')
helpers.parseHtml = require('./parseHtml')
helpers.round = require('./round')
helpers.sentimentColor = require('./sentimentColor')
helpers.tickerColor = require('./tickerColor')
helpers.times = require('./times')
helpers.truncate = require('./truncate')