module.exports = [
  "cryptocurrency",
  "blockchain",
  "bitcoin",
  "ethereum",
  "altcoin",
  "bitcoin cash",
  "ripple coin",
  "litecoin",
  "dash coin",
  "bitconnect",
  "neo coin",
  "nem coin",
  "monero",
  "iota coin",
  "qtum coin",
  "cardano coin",
  "initial coin offering",
  "ICO",
  "currency mining",
  "SegWit2x"
]